function collectModelTestingResults()
    % metric capability added in R2020a
    if exist('metric')
        metricIDs = [...
        "ConditionCoverageBreakdown" "CoverageDataService"...
        "DecisionCoverageBreakdown" "ExecutionCoverageBreakdown"...
        "MCDCCoverageBreakdown" "OverallConditionCoverage"...
        "OverallDecisionCoverage" "OverallExecutionCoverage"...
        "OverallMCDCCoverage" "RequirementWithTestCase"...
        "RequirementWithTestCaseDistribution" "RequirementWithTestCasePercentage"...
        "RequirementsPerTestCase" "RequirementsPerTestCaseDistribution"...
        "TestCaseStatus" "TestCaseStatusDistribution"...
        "TestCaseStatusPercentage" "TestCaseTag"...
        "TestCaseTagDistribution" "TestCaseType"...
        "TestCaseTypeDistribution" "TestCaseWithRequirement"...
        "TestCaseWithRequirementDistribution" "TestCaseWithRequirementPercentage"...
        "TestCasesPerRequirement" "TestCasesPerRequirementDistribution"...
        ];
        % collect all metrics for initial reconcile
        E = metric.Engine();
        execute(E, metricIDs);
    end
end